
import { Country } from './types';

export const COUNTRIES: Country[] = [
  { code: 'AF', nameAr: 'أفغانستان', nameEn: 'Afghanistan', flag: '🇦🇫', currencyCode: 'AFN', color: '#000000' },
  { code: 'AL', nameAr: 'ألبانيا', nameEn: 'Albania', flag: '🇦🇱', currencyCode: 'ALL', color: '#E41E20' },
  { code: 'DZ', nameAr: 'الجزائر', nameEn: 'Algeria', flag: '🇩🇿', currencyCode: 'DZD', color: '#006233' },
  { code: 'AS', nameAr: 'ساموا الأمريكية', nameEn: 'American Samoa', flag: '🇦🇸', currencyCode: 'USD', color: '#002395' },
  { code: 'AD', nameAr: 'أندورا', nameEn: 'Andorra', flag: '🇦🇩', currencyCode: 'EUR', color: '#0018A8' },
  { code: 'AO', nameAr: 'أنغولا', nameEn: 'Angola', flag: '🇦🇴', currencyCode: 'AOA', color: '#CE1126' },
  { code: 'AI', nameAr: 'أنغويلا', nameEn: 'Anguilla', flag: '🇦🇮', currencyCode: 'XCD', color: '#005896' },
  { code: 'AG', nameAr: 'أنتيغوا وبربودا', nameEn: 'Antigua and Barbuda', flag: '🇦🇬', currencyCode: 'XCD', color: '#CE1126' },
  { code: 'AR', nameAr: 'الأرجنتين', nameEn: 'Argentina', flag: '🇦🇷', currencyCode: 'ARS', color: '#75AADB' },
  { code: 'AM', nameAr: 'أرمينيا', nameEn: 'Armenia', flag: '🇦🇲', currencyCode: 'AMD', color: '#D90012' },
  { code: 'AW', nameAr: 'أروبا', nameEn: 'Aruba', flag: '🇦🇼', currencyCode: 'AWG', color: '#4189DD' },
  { code: 'AU', nameAr: 'أستراليا', nameEn: 'Australia', flag: '🇦🇺', currencyCode: 'AUD', color: '#00008B' },
  { code: 'AT', nameAr: 'النمسا', nameEn: 'Austria', flag: '🇦🇹', currencyCode: 'EUR', color: '#ED2939' },
  { code: 'AZ', nameAr: 'أذربيجان', nameEn: 'Azerbaijan', flag: '🇦🇿', currencyCode: 'AZN', color: '#00B5E2' },
  { code: 'BS', nameAr: 'جزر البهاما', nameEn: 'Bahamas', flag: '🇧🇸', currencyCode: 'BSD', color: '#00778B' },
  { code: 'BH', nameAr: 'البحرين', nameEn: 'Bahrain', flag: '🇧🇭', currencyCode: 'BHD', color: '#CE1126' },
  { code: 'BD', nameAr: 'بنغلاديش', nameEn: 'Bangladesh', flag: '🇧🇩', currencyCode: 'BDT', color: '#006A4E' },
  { code: 'BB', nameAr: 'باربادوس', nameEn: 'Barbados', flag: '🇧🇧', currencyCode: 'BBD', color: '#00267F' },
  { code: 'BY', nameAr: 'بيلاروسيا', nameEn: 'Belarus', flag: '🇧🇾', currencyCode: 'BYN', color: '#C8102E' },
  { code: 'BE', nameAr: 'بلجيكا', nameEn: 'Belgium', flag: '🇧🇪', currencyCode: 'EUR', color: '#000000' },
  { code: 'BZ', nameAr: 'بليز', nameEn: 'Belize', flag: '🇧🇿', currencyCode: 'BZD', color: '#003F87' },
  { code: 'BJ', nameAr: 'بنين', nameEn: 'Benin', flag: '🇧🇯', currencyCode: 'XOF', color: '#E8112D' },
  { code: 'BM', nameAr: 'برمودا', nameEn: 'Bermuda', flag: '🇧🇲', currencyCode: 'BMD', color: '#E41E20' },
  { code: 'BT', nameAr: 'بوتان', nameEn: 'Bhutan', flag: '🇧🇹', currencyCode: 'BTN', color: '#FF4E12' },
  { code: 'BO', nameAr: 'بوليفيا', nameEn: 'Bolivia', flag: '🇧🇴', currencyCode: 'BOB', color: '#007A33' },
  { code: 'BA', nameAr: 'البوسنة والهرسك', nameEn: 'Bosnia and Herzegovina', flag: '🇧🇦', currencyCode: 'BAM', color: '#002395' },
  { code: 'BW', nameAr: 'بوتسوانا', nameEn: 'Botswana', flag: '🇧🇼', currencyCode: 'BWP', color: '#00CBFF' },
  { code: 'BR', nameAr: 'البرازيل', nameEn: 'Brazil', flag: '🇧🇷', currencyCode: 'BRL', color: '#009C3B' },
  { code: 'BN', nameAr: 'بروناي', nameEn: 'Brunei', flag: '🇧🇳', currencyCode: 'BND', color: '#F7E017' },
  { code: 'BG', nameAr: 'بلغاريا', nameEn: 'Bulgaria', flag: '🇧🇬', currencyCode: 'BGN', color: '#00966E' },
  { code: 'BF', nameAr: 'بوركينا فاسو', nameEn: 'Burkina Faso', flag: '🇧🇫', currencyCode: 'XOF', color: '#EF2B2D' },
  { code: 'BI', nameAr: 'بوروندي', nameEn: 'Burundi', flag: '🇧🇮', currencyCode: 'BIF', color: '#CE1126' },
  { code: 'KH', nameAr: 'كمبوديا', nameEn: 'Cambodia', flag: '🇰🇭', currencyCode: 'KHR', color: '#E00025' },
  { code: 'CM', nameAr: 'الكاميرون', nameEn: 'Cameroon', flag: '🇨🇲', currencyCode: 'XAF', color: '#007A5E' },
  { code: 'CA', nameAr: 'كندا', nameEn: 'Canada', flag: '🇨🇦', currencyCode: 'CAD', color: '#D80621' },
  { code: 'CV', nameAr: 'الرأس الأخضر', nameEn: 'Cape Verde', flag: '🇨🇻', currencyCode: 'CVE', color: '#003893' },
  { code: 'KY', nameAr: 'جزر كايمان', nameEn: 'Cayman Islands', flag: '🇰🇾', currencyCode: 'KYD', color: '#002395' },
  { code: 'CF', nameAr: 'جمهورية أفريقيا الوسطى', nameEn: 'Central African Republic', flag: '🇨🇫', currencyCode: 'XAF', color: '#003082' },
  { code: 'TD', nameAr: 'تشاد', nameEn: 'Chad', flag: '🇹🇩', currencyCode: 'XAF', color: '#002664' },
  { code: 'CL', nameAr: 'تشيلي', nameEn: 'Chile', flag: '🇨🇱', currencyCode: 'CLP', color: '#0039A6' },
  { code: 'CN', nameAr: 'الصين', nameEn: 'China', flag: '🇨🇳', currencyCode: 'CNY', color: '#DE2910' },
  { code: 'CO', nameAr: 'كولومبيا', nameEn: 'Colombia', flag: '🇨🇴', currencyCode: 'COP', color: '#FCD116' },
  { code: 'KM', nameAr: 'جزر القمر', nameEn: 'Comoros', flag: '🇰🇲', currencyCode: 'KMF', color: '#3D8E33' },
  { code: 'CG', nameAr: 'الكونغو', nameEn: 'Congo', flag: '🇨🇬', currencyCode: 'XAF', color: '#FBDE4A' },
  { code: 'CD', nameAr: 'جمهورية الكونغو الديمقراطية', nameEn: 'DR Congo', flag: '🇨🇩', currencyCode: 'CDF', color: '#007FFF' },
  { code: 'CR', nameAr: 'كوستاريكا', nameEn: 'Costa Rica', flag: '🇨🇷', currencyCode: 'CRC', color: '#002B7F' },
  { code: 'HR', nameAr: 'كرواتيا', nameEn: 'Croatia', flag: '🇭🇷', currencyCode: 'EUR', color: '#FF0000' },
  { code: 'CU', nameAr: 'كوبا', nameEn: 'Cuba', flag: '🇨🇺', currencyCode: 'CUP', color: '#CC0D0D' },
  { code: 'CY', nameAr: 'قبرص', nameEn: 'Cyprus', flag: '🇨🇾', currencyCode: 'EUR', color: '#D57800' },
  { code: 'CZ', nameAr: 'التشيك', nameEn: 'Czech Republic', flag: '🇨🇿', currencyCode: 'CZK', color: '#11457E' },
  { code: 'DK', nameAr: 'الدانمارك', nameEn: 'Denmark', flag: '🇩🇰', currencyCode: 'DKK', color: '#C60C30' },
  { code: 'DJ', nameAr: 'جيبوتي', nameEn: 'Djibouti', flag: '🇩🇯', currencyCode: 'DJF', color: '#6AB2E7' },
  { code: 'DM', nameAr: 'دومينيكا', nameEn: 'Dominica', flag: '🇩🇲', currencyCode: 'XCD', color: '#006B3F' },
  { code: 'DO', nameAr: 'جمهورية الدومينيكان', nameEn: 'Dominican Republic', flag: '🇩🇴', currencyCode: 'DOP', color: '#002D62' },
  { code: 'EC', nameAr: 'الإكوادور', nameEn: 'Ecuador', flag: '🇪🇨', currencyCode: 'USD', color: '#FFDD00' },
  { code: 'EG', nameAr: 'مصر', nameEn: 'Egypt', flag: '🇪🇬', currencyCode: 'EGP', color: '#CE1126' },
  { code: 'SV', nameAr: 'السلفادور', nameEn: 'El Salvador', flag: '🇸🇻', currencyCode: 'USD', color: '#0047AB' },
  { code: 'GQ', nameAr: 'غينيا الاستوائية', nameEn: 'Equatorial Guinea', flag: '🇬🇶', currencyCode: 'XAF', color: '#3DED97' },
  { code: 'ER', nameAr: 'إريتريا', nameEn: 'Eritrea', flag: '🇪🇷', currencyCode: 'ERN', color: '#EB1C24' },
  { code: 'EE', nameAr: 'إستونيا', nameEn: 'Estonia', flag: '🇪🇪', currencyCode: 'EUR', color: '#0072CE' },
  { code: 'SZ', nameAr: 'إسواتيني', nameEn: 'Eswatini', flag: '🇸🇿', currencyCode: 'SZL', color: '#B10C0C' },
  { code: 'ET', nameAr: 'إثيوبيا', nameEn: 'Ethiopia', flag: '🇪🇹', currencyCode: 'ETB', color: '#078930' },
  { code: 'FJ', nameAr: 'فيجي', nameEn: 'Fiji', flag: '🇫🇯', currencyCode: 'FJD', color: '#68BFE5' },
  { code: 'FI', nameAr: 'فنلندا', nameEn: 'Finland', flag: '🇫🇮', currencyCode: 'EUR', color: '#003580' },
  { code: 'FR', nameAr: 'فرنسا', nameEn: 'France', flag: '🇫🇷', currencyCode: 'EUR', color: '#0055A4' },
  { code: 'GA', nameAr: 'الغابون', nameEn: 'Gabon', flag: '🇬🇦', currencyCode: 'XAF', color: '#36A100' },
  { code: 'GM', nameAr: 'غامبيا', nameEn: 'Gambia', flag: '🇬🇲', currencyCode: 'GMD', color: '#CE1126' },
  { code: 'GE', nameAr: 'جورجيا', nameEn: 'Georgia', flag: '🇬🇪', currencyCode: 'GEL', color: '#FF0000' },
  { code: 'DE', nameAr: 'ألمانيا', nameEn: 'Germany', flag: '🇩🇪', currencyCode: 'EUR', color: '#DD0000' },
  { code: 'GH', nameAr: 'غانا', nameEn: 'Ghana', flag: '🇬🇭', currencyCode: 'GHS', color: '#EF3340' },
  { code: 'GI', nameAr: 'جبل طارق', nameEn: 'Gibraltar', flag: '🇬🇮', currencyCode: 'GIP', color: '#CE1126' },
  { code: 'GR', nameAr: 'اليونان', nameEn: 'Greece', flag: '🇬🇷', currencyCode: 'EUR', color: '#0D5EAF' },
  { code: 'GD', nameAr: 'غرينادا', nameEn: 'Grenada', flag: '🇬🇩', currencyCode: 'XCD', color: '#CE1126' },
  { code: 'GT', nameAr: 'غواتيمالا', nameEn: 'Guatemala', flag: '🇬🇹', currencyCode: 'GTQ', color: '#4997D0' },
  { code: 'GN', nameAr: 'غينيا', nameEn: 'Guinea', flag: '🇬🇳', currencyCode: 'GNF', color: '#CE1126' },
  { code: 'GW', nameAr: 'غينيا بيساو', nameEn: 'Guinea-Bissau', flag: '🇬🇼', currencyCode: 'XOF', color: '#CE1126' },
  { code: 'GY', nameAr: 'غيانا', nameEn: 'Guyana', flag: '🇬🇾', currencyCode: 'GYD', color: '#009E49' },
  { code: 'HT', nameAr: 'هاييتي', nameEn: 'Haiti', flag: '🇭🇹', currencyCode: 'HTG', color: '#00209F' },
  { code: 'HN', nameAr: 'هندوراس', nameEn: 'Honduras', flag: '🇭🇳', currencyCode: 'HNL', color: '#0073CF' },
  { code: 'HK', nameAr: 'هونغ كونغ', nameEn: 'Hong Kong', flag: '🇭🇰', currencyCode: 'HKD', color: '#DE2910' },
  { code: 'HU', nameAr: 'المجر', nameEn: 'Hungary', flag: '🇭🇺', currencyCode: 'HUF', color: '#436F4D' },
  { code: 'IS', nameAr: 'أيسلندا', nameEn: 'Iceland', flag: '🇮🇸', currencyCode: 'ISK', color: '#02529C' },
  { code: 'IN', nameAr: 'الهند', nameEn: 'India', flag: '🇮🇳', currencyCode: 'INR', color: '#FF9933' },
  { code: 'ID', nameAr: 'إندونيسيا', nameEn: 'Indonesia', flag: '🇮🇩', currencyCode: 'IDR', color: '#CE1126' },
  { code: 'IR', nameAr: 'إيران', nameEn: 'Iran', flag: '🇮🇷', currencyCode: 'IRR', color: '#239B56' },
  { code: 'IQ', nameAr: 'العراق', nameEn: 'Iraq', flag: '🇮🇶', currencyCode: 'IQD', color: '#CE1126' },
  { code: 'IE', nameAr: 'أيرلندا', nameEn: 'Ireland', flag: '🇮🇪', currencyCode: 'EUR', color: '#169B62' },
  { code: 'IT', nameAr: 'إيطاليا', nameEn: 'Italy', flag: '🇮🇹', currencyCode: 'EUR', color: '#008C45' },
  { code: 'JM', nameAr: 'جامايكا', nameEn: 'Jamaica', flag: '🇯🇲', currencyCode: 'JMD', color: '#009B3A' },
  { code: 'JP', nameAr: 'اليابان', nameEn: 'Japan', flag: '🇯🇵', currencyCode: 'JPY', color: '#BC002D' },
  { code: 'JO', nameAr: 'الأردن', nameEn: 'Jordan', flag: '🇯🇴', currencyCode: 'JOD', color: '#007A3D' },
  { code: 'KZ', nameAr: 'كازاخستان', nameEn: 'Kazakhstan', flag: '🇰🇿', currencyCode: 'KZT', color: '#00AFCA' },
  { code: 'KE', nameAr: 'كينيا', nameEn: 'Kenya', flag: '🇰🇪', currencyCode: 'KES', color: '#000000' },
  { code: 'KW', nameAr: 'الكويت', nameEn: 'Kuwait', flag: '🇰🇼', currencyCode: 'KWD', color: '#007A3D' },
  { code: 'KG', nameAr: 'قيرغيزستان', nameEn: 'Kyrgyzstan', flag: '🇰🇬', currencyCode: 'KGS', color: '#E1111A' },
  { code: 'LA', nameAr: 'لاوس', nameEn: 'Laos', flag: '🇱🇦', currencyCode: 'LAK', color: '#002868' },
  { code: 'LV', nameAr: 'لاتفيا', nameEn: 'Latvia', flag: '🇱🇻', currencyCode: 'EUR', color: '#9E3039' },
  { code: 'LB', nameAr: 'لبنان', nameEn: 'Lebanon', flag: '🇱🇧', currencyCode: 'LBP', color: '#ED1C24' },
  { code: 'LS', nameAr: 'ليسوتو', nameEn: 'Lesotho', flag: '🇱🇸', currencyCode: 'LSL', color: '#00209F' },
  { code: 'LR', nameAr: 'ليبيريا', nameEn: 'Liberia', flag: '🇱🇷', currencyCode: 'LRD', color: '#BF0A30' },
  { code: 'LY', nameAr: 'ليبيا', nameEn: 'Libya', flag: '🇱🇾', currencyCode: 'LYD', color: '#239B56' },
  { code: 'LI', nameAr: 'ليختنشتاين', nameEn: 'Liechtenstein', flag: '🇱🇮', currencyCode: 'CHF', color: '#002780' },
  { code: 'LT', nameAr: 'ليتوانيا', nameEn: 'Lithuania', flag: '🇱🇹', currencyCode: 'EUR', color: '#FDB913' },
  { code: 'LU', nameAr: 'لوكسمبورغ', nameEn: 'Luxembourg', flag: '🇱🇺', currencyCode: 'EUR', color: '#00A1DE' },
  { code: 'MO', nameAr: 'ماكاو', nameEn: 'Macau', flag: '🇲🇴', currencyCode: 'MOP', color: '#00785E' },
  { code: 'MG', nameAr: 'مدغشقر', nameEn: 'Madagascar', flag: '🇲🇬', currencyCode: 'MGA', color: '#FC3D32' },
  { code: 'MW', nameAr: 'مالاوي', nameEn: 'Malawi', flag: '🇲🇼', currencyCode: 'MWK', color: '#CE1126' },
  { code: 'MY', nameAr: 'ماليزيا', nameEn: 'Malaysia', flag: '🇲🇾', currencyCode: 'MYR', color: '#010066' },
  { code: 'MV', nameAr: 'المالديف', nameEn: 'Maldives', flag: '🇲🇻', currencyCode: 'MVR', color: '#D11231' },
  { code: 'ML', nameAr: 'مالي', nameEn: 'Mali', flag: '🇲🇱', currencyCode: 'XOF', color: '#14B53A' },
  { code: 'MT', nameAr: 'مالطا', nameEn: 'Malta', flag: '🇲🇹', currencyCode: 'EUR', color: '#BF0024' },
  { code: 'MR', nameAr: 'موريتانيا', nameEn: 'Mauritania', flag: '🇲🇷', currencyCode: 'MRU', color: '#006233' },
  { code: 'MU', nameAr: 'موريشيوس', nameEn: 'Mauritius', flag: '🇲🇺', currencyCode: 'MUR', color: '#EA2839' },
  { code: 'MX', nameAr: 'المكسيك', nameEn: 'Mexico', flag: '🇲🇽', currencyCode: 'MXN', color: '#006847' },
  { code: 'MD', nameAr: 'مولدوفا', nameEn: 'Moldova', flag: '🇲🇩', currencyCode: 'MDL', color: '#0046AE' },
  { code: 'MC', nameAr: 'موناكو', nameEn: 'Monaco', flag: '🇲🇨', currencyCode: 'EUR', color: '#CE1126' },
  { code: 'MN', nameAr: 'منغوليا', nameEn: 'Mongolia', flag: '🇲🇳', currencyCode: 'MNT', color: '#E1111A' },
  { code: 'ME', nameAr: 'الجبل الأسود', nameEn: 'Montenegro', flag: '🇲🇪', currencyCode: 'EUR', color: '#C40308' },
  { code: 'MA', nameAr: 'المغرب', nameEn: 'Morocco', flag: '🇲🇦', currencyCode: 'MAD', color: '#C1272D' },
  { code: 'MZ', nameAr: 'موزمبيق', nameEn: 'Mozambique', flag: '🇲🇿', currencyCode: 'MZN', color: '#009739' },
  { code: 'MM', nameAr: 'ميانمار', nameEn: 'Myanmar', flag: '🇲🇲', currencyCode: 'MMK', color: '#FECB00' },
  { code: 'NA', nameAr: 'ناميبيا', nameEn: 'Namibia', flag: '🇳🇦', currencyCode: 'NAD', color: '#003580' },
  { code: 'NP', nameAr: 'نيبال', nameEn: 'Nepal', flag: '🇳🇵', currencyCode: 'NPR', color: '#DC143C' },
  { code: 'NL', nameAr: 'هولندا', nameEn: 'Netherlands', flag: '🇳🇱', currencyCode: 'EUR', color: '#21468B' },
  { code: 'NZ', nameAr: 'نيوزيلندا', nameEn: 'New Zealand', flag: '🇳🇿', currencyCode: 'NZD', color: '#00247D' },
  { code: 'NI', nameAr: 'نيكاراغوا', nameEn: 'Nicaragua', flag: '🇳🇮', currencyCode: 'NIO', color: '#0067C6' },
  { code: 'NE', nameAr: 'النيجر', nameEn: 'Niger', flag: '🇳🇪', currencyCode: 'XOF', color: '#E05206' },
  { code: 'NG', nameAr: 'نيجيريا', nameEn: 'Nigeria', flag: '🇳🇬', currencyCode: 'NGN', color: '#008751' },
  { code: 'KP', nameAr: 'كوريا الشمالية', nameEn: 'North Korea', flag: '🇰🇵', currencyCode: 'KPW', color: '#ED1C27' },
  { code: 'MK', nameAr: 'مقدونيا الشمالية', nameEn: 'North Macedonia', flag: '🇲🇰', currencyCode: 'MKD', color: '#D20000' },
  { code: 'NO', nameAr: 'النرويج', nameEn: 'Norway', flag: '🇳🇴', currencyCode: 'NOK', color: '#BA0C2F' },
  { code: 'OM', nameAr: 'عمان', nameEn: 'Oman', flag: '🇴🇲', currencyCode: 'OMR', color: '#DB161B' },
  { code: 'PK', nameAr: 'باكستان', nameEn: 'Pakistan', flag: '🇵🇰', currencyCode: 'PKR', color: '#115740' },
  { code: 'PS', nameAr: 'فلسطين', nameEn: 'Palestine', flag: '🇵🇸', currencyCode: 'ILS', color: '#000000' },
  { code: 'PA', nameAr: 'بنما', nameEn: 'Panama', flag: '🇵🇦', currencyCode: 'USD', color: '#005293' },
  { code: 'PY', nameAr: 'باراغواي', nameEn: 'Paraguay', flag: '🇵🇾', currencyCode: 'PYG', color: '#D52B1E' },
  { code: 'PE', nameAr: 'بيرو', nameEn: 'Peru', flag: '🇵🇪', currencyCode: 'PEN', color: '#D91023' },
  { code: 'PH', nameAr: 'الفلبين', nameEn: 'Philippines', flag: '🇵🇭', currencyCode: 'PHP', color: '#0038A8' },
  { code: 'PL', nameAr: 'بولندا', nameEn: 'Poland', flag: '🇵🇱', currencyCode: 'PLN', color: '#DC143C' },
  { code: 'PT', nameAr: 'البرتغال', nameEn: 'Portugal', flag: '🇵🇹', currencyCode: 'EUR', color: '#006600' },
  { code: 'PR', nameAr: 'بورتوريكو', nameEn: 'Puerto Rico', flag: '🇵🇷', currencyCode: 'USD', color: '#002B7E' },
  { code: 'QA', nameAr: 'قطر', nameEn: 'Qatar', flag: '🇶🇦', currencyCode: 'QAR', color: '#8D1B3D' },
  { code: 'RO', nameAr: 'رومانيا', nameEn: 'Romania', flag: '🇷🇴', currencyCode: 'RON', color: '#002B7F' },
  { code: 'RU', nameAr: 'روسيا', nameEn: 'Russia', flag: '🇷🇺', currencyCode: 'RUB', color: '#0039A6' },
  { code: 'RW', nameAr: 'رواندا', nameEn: 'Rwanda', flag: '🇷🇼', currencyCode: 'RWF', color: '#00A1DE' },
  { code: 'SA', nameAr: 'المملكة العربية السعودية', nameEn: 'Saudi Arabia', flag: '🇸🇦', currencyCode: 'SAR', color: '#165D31' },
  { code: 'SN', nameAr: 'السنغال', nameEn: 'Senegal', flag: '🇸🇳', currencyCode: 'XOF', color: '#00853F' },
  { code: 'RS', nameAr: 'صربيا', nameEn: 'Serbia', flag: '🇷🇸', currencyCode: 'RSD', color: '#C6363C' },
  { code: 'SC', nameAr: 'سيشيل', nameEn: 'Seychelles', flag: '🇸🇨', currencyCode: 'SCR', color: '#003D88' },
  { code: 'SG', nameAr: 'سنغافورة', nameEn: 'Singapore', flag: '🇸🇬', currencyCode: 'SGD', color: '#ED2939' },
  { code: 'SK', nameAr: 'سلوفاكيا', nameEn: 'Slovakia', flag: '🇸🇰', currencyCode: 'EUR', color: '#0B4EA2' },
  { code: 'SI', nameAr: 'سلوفينيا', nameEn: 'Slovenia', flag: '🇸🇮', currencyCode: 'EUR', color: '#002395' },
  { code: 'SO', nameAr: 'الصومال', nameEn: 'Somalia', flag: '🇸🇴', currencyCode: 'SOS', color: '#4189DD' },
  { code: 'ZA', nameAr: 'جنوب أفريقيا', nameEn: 'South Africa', flag: '🇿🇦', currencyCode: 'ZAR', color: '#007749' },
  { code: 'KR', nameAr: 'كوريا الجنوبية', nameEn: 'South Korea', flag: '🇰🇷', currencyCode: 'KRW', color: '#0F64CD' },
  { code: 'ES', nameAr: 'إسبانيا', nameEn: 'Spain', flag: '🇪🇸', currencyCode: 'EUR', color: '#AA151B' },
  { code: 'LK', nameAr: 'سريلانكا', nameEn: 'Sri Lanka', flag: '🇱🇰', currencyCode: 'LKR', color: '#8D153A' },
  { code: 'SD', nameAr: 'السودان', nameEn: 'Sudan', flag: '🇸🇩', currencyCode: 'SDG', color: '#007229' },
  { code: 'SE', nameAr: 'السويد', nameEn: 'Sweden', flag: '🇸🇪', currencyCode: 'SEK', color: '#006AA7' },
  { code: 'CH', nameAr: 'سويسرا', nameEn: 'Switzerland', flag: '🇨🇭', currencyCode: 'CHF', color: '#D52B1E' },
  { code: 'SY', nameAr: 'سوريا', nameEn: 'Syria', flag: '🇸🇾', currencyCode: 'SYP', color: '#CE1126' },
  { code: 'TW', nameAr: 'تايوان', nameEn: 'Taiwan', flag: '🇹🇼', currencyCode: 'TWD', color: '#FE0000' },
  { code: 'TZ', nameAr: 'تنزانيا', nameEn: 'Tanzania', flag: '🇹🇿', currencyCode: 'TZS', color: '#1EB53A' },
  { code: 'TH', nameAr: 'تايلاند', nameEn: 'Thailand', flag: '🇹🇭', currencyCode: 'THB', color: '#241D4F' },
  { code: 'TN', nameAr: 'تونس', nameEn: 'Tunisia', flag: '🇹🇳', currencyCode: 'TND', color: '#E70013' },
  { code: 'TR', nameAr: 'تركيا', nameEn: 'Turkey', flag: '🇹🇷', currencyCode: 'TRY', color: '#E30A17' },
  { code: 'UG', nameAr: 'أوغندا', nameEn: 'Uganda', flag: '🇺🇬', currencyCode: 'UGX', color: '#000000' },
  { code: 'UA', nameAr: 'أوكرانيا', nameEn: 'Ukraine', flag: '🇺🇦', currencyCode: 'UAH', color: '#0057B7' },
  { code: 'AE', nameAr: 'الإمارات العربية المتحدة', nameEn: 'United Arab Emirates', flag: '🇦🇪', currencyCode: 'AED', color: '#00732F' },
  { code: 'GB', nameAr: 'المملكة المتحدة', nameEn: 'United Kingdom', flag: '🇬🇧', currencyCode: 'GBP', color: '#012169' },
  { code: 'US', nameAr: 'الولايات المتحدة الأمريكية', nameEn: 'United States', flag: '🇺🇸', currencyCode: 'USD', color: '#3C3B6E' },
  { code: 'UY', nameAr: 'أوروغواي', nameEn: 'Uruguay', flag: '🇺🇾', currencyCode: 'UYU', color: '#0038A8' },
  { code: 'UZ', nameAr: 'أوزبكستان', nameEn: 'Uzbekistan', flag: '🇺🇿', currencyCode: 'UZS', color: '#0099B5' },
  { code: 'VE', nameAr: 'فنزويلا', nameEn: 'Venezuela', flag: '🇻🇪', currencyCode: 'VES', color: '#FCE300' },
  { code: 'VN', nameAr: 'فيتنام', nameEn: 'Vietnam', flag: '🇻🇳', currencyCode: 'VND', color: '#DA251D' },
  { code: 'YE', nameAr: 'اليمن', nameEn: 'Yemen', flag: '🇾🇪', currencyCode: 'YER', color: '#CE1126' },
  { code: 'ZM', nameAr: 'زامبيا', nameEn: 'Zambia', flag: '🇿🇲', currencyCode: 'ZMW', color: '#198A00' },
  { code: 'ZW', nameAr: 'زيمبابوي', nameEn: 'Zimbabwe', flag: '🇿🇼', currencyCode: 'ZWL', color: '#006400' },
].sort((a, b) => a.nameAr.localeCompare(b.nameAr, 'ar'));

// Approximate Exchange Rates relative to 1 USD
export const EXCHANGE_RATES: Record<string, number> = {
  'USD': 1,
  'EUR': 0.92,
  'GBP': 0.78,
  'SAR': 3.75,
  'AED': 3.67,
  'EGP': 49.5,
  'TRY': 34.2,
  'JPY': 152,
  'CNY': 7.2,
  'INR': 84.4,
  'QAR': 3.64,
  'KWD': 0.31,
  'BHD': 0.38,
  'OMR': 0.385,
  'JOD': 0.71,
  'LBP': 89500,
  'MAD': 10.1,
  'DZD': 134,
  'TND': 3.1,
  'MYR': 4.4,
  'IDR': 15700,
  'THB': 34.5,
  'SGD': 1.33,
  'KRW': 1380,
  'RUB': 97,
  'CAD': 1.39,
  'AUD': 1.52,
  'BRL': 5.75,
  'ZAR': 17.8,
  'CHF': 0.88,
  'SEK': 10.8,
  'NOK': 11.0,
  'DKK': 6.9,
  'MVR': 15.4,
  'GEL': 2.72,
  'AZN': 1.7,
  'AMD': 387,
  'LKR': 293,
  'PHP': 58,
  'VND': 25300,
  'MXN': 20.2,
  'ARS': 990,
  'NZD': 1.67,
  'PKR': 278,
  'BDT': 120,
  'NGN': 1650,
  'PLN': 4.05,
  'UAH': 41.3,
  'ALL': 92.5,
  'RWF': 1360,
  'KES': 129,
  'BGN': 1.8,
  'CRC': 505,
  'BZD': 2.0,
  'GTQ': 7.7,
  'HNL': 24.7,
  'DOP': 59.0,
  'BMD': 1.0,
  'XCD': 2.7,
  'MKD': 56.5,
  'CZK': 23.5,
  'HUF': 370,
  'RON': 4.6,
  'ISK': 137,
  'RSD': 117,
  'BAM': 1.8,
  'UZS': 12600,
  'KZT': 450,
  'HKD': 7.8,
  'TWD': 32.5,
  'COP': 4400,
  'PEN': 3.75,
  'CLP': 980,
  'NPR': 135,
  'TZS': 2600,
  'SCR': 13.5,
  'MUR': 46.5
};
